backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Artículos del blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Noticias", "Eventos", "Vida Universitaria", "Opinión"] }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }